name: textiffi
description: "OCR Application using Dart ffi"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  get_it: ^7.6.7
  dartz: ^0.10.1
  http: ^1.2.1
  flutter_bloc: ^8.1.4
  path: ^1.9.0
  meta: ^1.11.0
  mockito: ^5.4.4
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.1
  json_serializable: ^6.7.1
  url_launcher: ^6.2.5
  path_provider: ^2.1.2
  go_router: ^13.2.0
  permission_handler: ^11.3.0
  equatable: ^2.0.5
  copy_with_extension: ^5.0.4
  image_picker: ^1.0.7

dev_dependencies:
  build_runner: ^2.4.8
  build_verify: ^3.1.0
  copy_with_extension_gen: ^5.0.4
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.4.1
  integration_test:
    sdk: flutter
  mocktail: ^1.0.3
  sqflite_common_ffi: ^2.3.2+1

flutter:

  uses-material-design: true

  assets:
    - assets/images/


